//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class mondial {
    
    private country[] countryField;
    
    private continent[] continentField;
    
    private organization[] organizationField;
    
    private sea[] seaField;
    
    private river[] riverField;
    
    private lake[] lakeField;
    
    private island[] islandField;
    
    private mountain[] mountainField;
    
    private desert[] desertField;
    
    private airport[] airportField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("country")]
    public country[] country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("continent")]
    public continent[] continent {
        get {
            return this.continentField;
        }
        set {
            this.continentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("organization")]
    public organization[] organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sea")]
    public sea[] sea {
        get {
            return this.seaField;
        }
        set {
            this.seaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("river")]
    public river[] river {
        get {
            return this.riverField;
        }
        set {
            this.riverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lake")]
    public lake[] lake {
        get {
            return this.lakeField;
        }
        set {
            this.lakeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("island")]
    public island[] island {
        get {
            return this.islandField;
        }
        set {
            this.islandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mountain")]
    public mountain[] mountain {
        get {
            return this.mountainField;
        }
        set {
            this.mountainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("desert")]
    public desert[] desert {
        get {
            return this.desertField;
        }
        set {
            this.desertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("airport")]
    public airport[] airport {
        get {
            return this.airportField;
        }
        set {
            this.airportField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class country {
    
    private string[] nameField;
    
    private string localnameField;
    
    private population[] populationField;
    
    private decimal population_growthField;
    
    private bool population_growthFieldSpecified;
    
    private decimal infant_mortalityField;
    
    private bool infant_mortalityFieldSpecified;
    
    private decimal gdp_totalField;
    
    private bool gdp_totalFieldSpecified;
    
    private decimal gdp_agriField;
    
    private bool gdp_agriFieldSpecified;
    
    private decimal gdp_indField;
    
    private bool gdp_indFieldSpecified;
    
    private decimal gdp_servField;
    
    private bool gdp_servFieldSpecified;
    
    private decimal inflationField;
    
    private bool inflationFieldSpecified;
    
    private decimal unemploymentField;
    
    private bool unemploymentFieldSpecified;
    
    private object itemField;
    
    private string governmentField;
    
    private encompassed[] encompassedField;
    
    private percentageproperty[] ethnicgroupField;
    
    private percentageproperty[] religionField;
    
    private percentageproperty[] languageField;
    
    private border[] borderField;
    
    private object[] itemsField;
    
    private string car_codeField;
    
    private decimal areaField;
    
    private bool areaFieldSpecified;
    
    private string capitalField;
    
    private string membershipsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string localname {
        get {
            return this.localnameField;
        }
        set {
            this.localnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("population")]
    public population[] population {
        get {
            return this.populationField;
        }
        set {
            this.populationField = value;
        }
    }
    
    /// <remarks/>
    public decimal population_growth {
        get {
            return this.population_growthField;
        }
        set {
            this.population_growthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool population_growthSpecified {
        get {
            return this.population_growthFieldSpecified;
        }
        set {
            this.population_growthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal infant_mortality {
        get {
            return this.infant_mortalityField;
        }
        set {
            this.infant_mortalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool infant_mortalitySpecified {
        get {
            return this.infant_mortalityFieldSpecified;
        }
        set {
            this.infant_mortalityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal gdp_total {
        get {
            return this.gdp_totalField;
        }
        set {
            this.gdp_totalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gdp_totalSpecified {
        get {
            return this.gdp_totalFieldSpecified;
        }
        set {
            this.gdp_totalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal gdp_agri {
        get {
            return this.gdp_agriField;
        }
        set {
            this.gdp_agriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gdp_agriSpecified {
        get {
            return this.gdp_agriFieldSpecified;
        }
        set {
            this.gdp_agriFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal gdp_ind {
        get {
            return this.gdp_indField;
        }
        set {
            this.gdp_indField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gdp_indSpecified {
        get {
            return this.gdp_indFieldSpecified;
        }
        set {
            this.gdp_indFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal gdp_serv {
        get {
            return this.gdp_servField;
        }
        set {
            this.gdp_servField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gdp_servSpecified {
        get {
            return this.gdp_servFieldSpecified;
        }
        set {
            this.gdp_servFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal inflation {
        get {
            return this.inflationField;
        }
        set {
            this.inflationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool inflationSpecified {
        get {
            return this.inflationFieldSpecified;
        }
        set {
            this.inflationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal unemployment {
        get {
            return this.unemploymentField;
        }
        set {
            this.unemploymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool unemploymentSpecified {
        get {
            return this.unemploymentFieldSpecified;
        }
        set {
            this.unemploymentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dependent", typeof(dependent))]
    [System.Xml.Serialization.XmlElementAttribute("indep_date", typeof(indep_date))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public string government {
        get {
            return this.governmentField;
        }
        set {
            this.governmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("encompassed")]
    public encompassed[] encompassed {
        get {
            return this.encompassedField;
        }
        set {
            this.encompassedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ethnicgroup")]
    public percentageproperty[] ethnicgroup {
        get {
            return this.ethnicgroupField;
        }
        set {
            this.ethnicgroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("religion")]
    public percentageproperty[] religion {
        get {
            return this.religionField;
        }
        set {
            this.religionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("language")]
    public percentageproperty[] language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("border")]
    public border[] border {
        get {
            return this.borderField;
        }
        set {
            this.borderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("city", typeof(city))]
    [System.Xml.Serialization.XmlElementAttribute("province", typeof(province))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string car_code {
        get {
            return this.car_codeField;
        }
        set {
            this.car_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string capital {
        get {
            return this.capitalField;
        }
        set {
            this.capitalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string memberships {
        get {
            return this.membershipsField;
        }
        set {
            this.membershipsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class population {
    
    private string yearField;
    
    private string measuredField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string measured {
        get {
            return this.measuredField;
        }
        set {
            this.measuredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="nonNegativeInteger")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class dependent {
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class indep_date {
    
    private string fromField;
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class encompassed {
    
    private string continentField;
    
    private decimal percentageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string continent {
        get {
            return this.continentField;
        }
        set {
            this.continentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="percentage-property")]
[System.Xml.Serialization.XmlRootAttribute("ethnicgroup", Namespace="", IsNullable=false)]
public partial class percentageproperty {
    
    private decimal percentageField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class border {
    
    private string countryField;
    
    private decimal lengthField;
    
    private string justiceField;
    
    public border() {
        this.justiceField = "org-UN";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    [System.ComponentModel.DefaultValueAttribute("org-UN")]
    public string justice {
        get {
            return this.justiceField;
        }
        set {
            this.justiceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class city {
    
    private string[] nameField;
    
    private string localnameField;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal elevationField;
    
    private bool elevationFieldSpecified;
    
    private population[] populationField;
    
    private located_at[] located_atField;
    
    private located_on[] located_onField;
    
    private string idField;
    
    private string is_country_capField;
    
    private string is_state_capField;
    
    private string countryField;
    
    private string provinceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string localname {
        get {
            return this.localnameField;
        }
        set {
            this.localnameField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool elevationSpecified {
        get {
            return this.elevationFieldSpecified;
        }
        set {
            this.elevationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("population")]
    public population[] population {
        get {
            return this.populationField;
        }
        set {
            this.populationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located_at")]
    public located_at[] located_at {
        get {
            return this.located_atField;
        }
        set {
            this.located_atField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located_on")]
    public located_on[] located_on {
        get {
            return this.located_onField;
        }
        set {
            this.located_onField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string is_country_cap {
        get {
            return this.is_country_capField;
        }
        set {
            this.is_country_capField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string is_state_cap {
        get {
            return this.is_state_capField;
        }
        set {
            this.is_state_capField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class located_at {
    
    private located_atWatertype watertypeField;
    
    private string riverField;
    
    private string seaField;
    
    private string lakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public located_atWatertype watertype {
        get {
            return this.watertypeField;
        }
        set {
            this.watertypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string river {
        get {
            return this.riverField;
        }
        set {
            this.riverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string sea {
        get {
            return this.seaField;
        }
        set {
            this.seaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string lake {
        get {
            return this.lakeField;
        }
        set {
            this.lakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum located_atWatertype {
    
    /// <remarks/>
    river,
    
    /// <remarks/>
    sea,
    
    /// <remarks/>
    lake,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class located_on {
    
    private string islandField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string island {
        get {
            return this.islandField;
        }
        set {
            this.islandField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class province {
    
    private string[] nameField;
    
    private string localnameField;
    
    private decimal areaField;
    
    private bool areaFieldSpecified;
    
    private population[] populationField;
    
    private city[] cityField;
    
    private string idField;
    
    private string countryField;
    
    private string capitalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string localname {
        get {
            return this.localnameField;
        }
        set {
            this.localnameField = value;
        }
    }
    
    /// <remarks/>
    public decimal area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("population")]
    public population[] population {
        get {
            return this.populationField;
        }
        set {
            this.populationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("city")]
    public city[] city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string capital {
        get {
            return this.capitalField;
        }
        set {
            this.capitalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class continent {
    
    private string nameField;
    
    private decimal areaField;
    
    private bool areaFieldSpecified;
    
    private string idField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public decimal area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class organization {
    
    private string nameField;
    
    private string abbrevField;
    
    private System.DateTime establishedField;
    
    private bool establishedFieldSpecified;
    
    private members[] membersField;
    
    private string idField;
    
    private string headqField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string abbrev {
        get {
            return this.abbrevField;
        }
        set {
            this.abbrevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime established {
        get {
            return this.establishedField;
        }
        set {
            this.establishedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool establishedSpecified {
        get {
            return this.establishedFieldSpecified;
        }
        set {
            this.establishedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("members")]
    public members[] members {
        get {
            return this.membersField;
        }
        set {
            this.membersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string headq {
        get {
            return this.headqField;
        }
        set {
            this.headqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class members {
    
    private string typeField;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class sea {
    
    private string[] nameField;
    
    private located[] locatedField;
    
    private decimal areaField;
    
    private bool areaFieldSpecified;
    
    private decimal depthField;
    
    private bool depthFieldSpecified;
    
    private string idField;
    
    private string countryField;
    
    private string borderingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located")]
    public located[] located {
        get {
            return this.locatedField;
        }
        set {
            this.locatedField = value;
        }
    }
    
    /// <remarks/>
    public decimal area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal depth {
        get {
            return this.depthField;
        }
        set {
            this.depthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool depthSpecified {
        get {
            return this.depthFieldSpecified;
        }
        set {
            this.depthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string bordering {
        get {
            return this.borderingField;
        }
        set {
            this.borderingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class located {
    
    private string countryField;
    
    private string provinceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class river {
    
    private string[] nameField;
    
    private located[] locatedField;
    
    private through[] throughField;
    
    private to toField;
    
    private decimal areaField;
    
    private bool areaFieldSpecified;
    
    private decimal lengthField;
    
    private bool lengthFieldSpecified;
    
    private source sourceField;
    
    private estuary estuaryField;
    
    private string idField;
    
    private string countryField;
    
    private string islandField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located")]
    public located[] located {
        get {
            return this.locatedField;
        }
        set {
            this.locatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("through")]
    public through[] through {
        get {
            return this.throughField;
        }
        set {
            this.throughField = value;
        }
    }
    
    /// <remarks/>
    public to to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    public decimal area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lengthSpecified {
        get {
            return this.lengthFieldSpecified;
        }
        set {
            this.lengthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public source source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public estuary estuary {
        get {
            return this.estuaryField;
        }
        set {
            this.estuaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string island {
        get {
            return this.islandField;
        }
        set {
            this.islandField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class through {
    
    private string lakeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string lake {
        get {
            return this.lakeField;
        }
        set {
            this.lakeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class to {
    
    private located_atWatertype watertypeField;
    
    private string waterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public located_atWatertype watertype {
        get {
            return this.watertypeField;
        }
        set {
            this.watertypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string water {
        get {
            return this.waterField;
        }
        set {
            this.waterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class source {
    
    private string mountainsField;
    
    private located[] locatedField;
    
    private from fromField;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal elevationField;
    
    private bool elevationFieldSpecified;
    
    private string countryField;
    
    /// <remarks/>
    public string mountains {
        get {
            return this.mountainsField;
        }
        set {
            this.mountainsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located")]
    public located[] located {
        get {
            return this.locatedField;
        }
        set {
            this.locatedField = value;
        }
    }
    
    /// <remarks/>
    public from from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool elevationSpecified {
        get {
            return this.elevationFieldSpecified;
        }
        set {
            this.elevationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class from {
    
    private located_atWatertype watertypeField;
    
    private string waterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public located_atWatertype watertype {
        get {
            return this.watertypeField;
        }
        set {
            this.watertypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string water {
        get {
            return this.waterField;
        }
        set {
            this.waterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class estuary {
    
    private located[] locatedField;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal elevationField;
    
    private bool elevationFieldSpecified;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located")]
    public located[] located {
        get {
            return this.locatedField;
        }
        set {
            this.locatedField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool elevationSpecified {
        get {
            return this.elevationFieldSpecified;
        }
        set {
            this.elevationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class lake {
    
    private string[] nameField;
    
    private located[] locatedField;
    
    private to toField;
    
    private decimal areaField;
    
    private bool areaFieldSpecified;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal elevationField;
    
    private bool elevationFieldSpecified;
    
    private decimal depthField;
    
    private bool depthFieldSpecified;
    
    private decimal heightField;
    
    private bool heightFieldSpecified;
    
    private string idField;
    
    private string countryField;
    
    private string islandField;
    
    private decimal salinityField;
    
    private bool salinityFieldSpecified;
    
    private lakeType typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located")]
    public located[] located {
        get {
            return this.locatedField;
        }
        set {
            this.locatedField = value;
        }
    }
    
    /// <remarks/>
    public to to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    public decimal area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool elevationSpecified {
        get {
            return this.elevationFieldSpecified;
        }
        set {
            this.elevationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal depth {
        get {
            return this.depthField;
        }
        set {
            this.depthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool depthSpecified {
        get {
            return this.depthFieldSpecified;
        }
        set {
            this.depthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool heightSpecified {
        get {
            return this.heightFieldSpecified;
        }
        set {
            this.heightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string island {
        get {
            return this.islandField;
        }
        set {
            this.islandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal salinity {
        get {
            return this.salinityField;
        }
        set {
            this.salinityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool salinitySpecified {
        get {
            return this.salinityFieldSpecified;
        }
        set {
            this.salinityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public lakeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum lakeType {
    
    /// <remarks/>
    impact,
    
    /// <remarks/>
    crater,
    
    /// <remarks/>
    saline,
    
    /// <remarks/>
    artificial,
    
    /// <remarks/>
    caldera,
    
    /// <remarks/>
    acid,
    
    /// <remarks/>
    naturaldam,
    
    /// <remarks/>
    dam,
    
    /// <remarks/>
    asphalt,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class island {
    
    private string[] nameField;
    
    private string islandsField;
    
    private located[] locatedField;
    
    private decimal areaField;
    
    private bool areaFieldSpecified;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal elevationField;
    
    private bool elevationFieldSpecified;
    
    private string idField;
    
    private string countryField;
    
    private string seaField;
    
    private string lakeField;
    
    private string riverField;
    
    private islandType typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string islands {
        get {
            return this.islandsField;
        }
        set {
            this.islandsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located")]
    public located[] located {
        get {
            return this.locatedField;
        }
        set {
            this.locatedField = value;
        }
    }
    
    /// <remarks/>
    public decimal area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool elevationSpecified {
        get {
            return this.elevationFieldSpecified;
        }
        set {
            this.elevationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string sea {
        get {
            return this.seaField;
        }
        set {
            this.seaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string lake {
        get {
            return this.lakeField;
        }
        set {
            this.lakeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string river {
        get {
            return this.riverField;
        }
        set {
            this.riverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public islandType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum islandType {
    
    /// <remarks/>
    volcanic,
    
    /// <remarks/>
    coral,
    
    /// <remarks/>
    atoll,
    
    /// <remarks/>
    lime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class mountain {
    
    private string[] nameField;
    
    private string mountainsField;
    
    private located[] locatedField;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal elevationField;
    
    private bool elevationFieldSpecified;
    
    private string idField;
    
    private string countryField;
    
    private mountainType typeField;
    
    private bool typeFieldSpecified;
    
    private string islandField;
    
    private System.DateTime last_eruptionField;
    
    private bool last_eruptionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string mountains {
        get {
            return this.mountainsField;
        }
        set {
            this.mountainsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located")]
    public located[] located {
        get {
            return this.locatedField;
        }
        set {
            this.locatedField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool elevationSpecified {
        get {
            return this.elevationFieldSpecified;
        }
        set {
            this.elevationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public mountainType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string island {
        get {
            return this.islandField;
        }
        set {
            this.islandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime last_eruption {
        get {
            return this.last_eruptionField;
        }
        set {
            this.last_eruptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool last_eruptionSpecified {
        get {
            return this.last_eruptionFieldSpecified;
        }
        set {
            this.last_eruptionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum mountainType {
    
    /// <remarks/>
    volcanic,
    
    /// <remarks/>
    volcano,
    
    /// <remarks/>
    granite,
    
    /// <remarks/>
    monolith,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class desert {
    
    private string[] nameField;
    
    private located[] locatedField;
    
    private decimal areaField;
    
    private bool areaFieldSpecified;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private string idField;
    
    private string countryField;
    
    private string climateField;
    
    private string temperatureField;
    
    private desertType typeField;
    
    public desert() {
        this.climateField = "dry aride";
        this.temperatureField = "hot";
        this.typeField = desertType.sand;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located")]
    public located[] located {
        get {
            return this.locatedField;
        }
        set {
            this.locatedField = value;
        }
    }
    
    /// <remarks/>
    public decimal area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string climate {
        get {
            return this.climateField;
        }
        set {
            this.climateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    [System.ComponentModel.DefaultValueAttribute("hot")]
    public string temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(desertType.sand)]
    public desertType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum desertType {
    
    /// <remarks/>
    sand,
    
    /// <remarks/>
    salt,
    
    /// <remarks/>
    rocks,
    
    /// <remarks/>
    lime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class airport {
    
    private string[] nameField;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal elevationField;
    
    private bool elevationFieldSpecified;
    
    private decimal gmtOffsetField;
    
    private bool gmtOffsetFieldSpecified;
    
    private located_on[] located_onField;
    
    private string iatacodeField;
    
    private string cityField;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool elevationSpecified {
        get {
            return this.elevationFieldSpecified;
        }
        set {
            this.elevationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal gmtOffset {
        get {
            return this.gmtOffsetField;
        }
        set {
            this.gmtOffsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gmtOffsetSpecified {
        get {
            return this.gmtOffsetFieldSpecified;
        }
        set {
            this.gmtOffsetFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("located_on")]
    public located_on[] located_on {
        get {
            return this.located_onField;
        }
        set {
            this.located_onField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string iatacode {
        get {
            return this.iatacodeField;
        }
        set {
            this.iatacodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}
